### ISSUE TITLE
Not all records selected for Reconciling / Cleared are updated to selected status

### ISSUE THREAD

**Issue by NickWard999** [TheInfiniteKind/moneydance_open#42] opened 2021-04-26 15:26 UTC
Dell XPS, Window 10, 20H2, Build 19042.928, MoneyDance 3066 and prior at least as far back as 1626 see attached document, 

I had also opened, Issue #7 in this GitHub, but had closed it, as it appeared GitHub was not be used for issue tracking at that time.

**There are two cases that I have observed.**
1) When I add an adjustment to a mortgage account split transaction
2) When marking investment transactions that have come from a split in a chequing account, in this case a pay cheque.

**Mortgage Screenshots**
Add additional split lines ($0.11) in Mortgage Transaction
![3066 Mortgage Transaction In Cheque Register](https://user-images.githubusercontent.com/59615855/116107333-2dceaf00-a670-11eb-81b0-76f5daddc4a9.png)

Records Selected to be Cleared
![3066 Mortgage Register Select Recods To Reconcile](https://user-images.githubusercontent.com/59615855/116107531-5b1b5d00-a670-11eb-8409-b11d6c852b1e.png)

![3066 Mortgage Register Select Recods To Be Marked Cleared](https://user-images.githubusercontent.com/59615855/116107619-6bcbd300-a670-11eb-8df1-8f9b53ea451c.png)

The added split is not marked as cleared, I have to manually mark as cleared as a one time record.
![3066 Mortgage Register Adjusted Record Not Marked](https://user-images.githubusercontent.com/59615855/116107662-74bca480-a670-11eb-83a3-4a16dfa18339.png)

**Investment Account**

![3066 Investment Register Records from Split Pay Cheque](https://user-images.githubusercontent.com/59615855/116108193-eac10b80-a670-11eb-9b83-ac14e4afc7e3.png)

![3066 Investment Register Records from Split Pay Cheque Select Reconciling](https://user-images.githubusercontent.com/59615855/116108225-f1e81980-a670-11eb-941f-da060d09cdbc.png)

**Only one record is marked as cleared**
![3066 Investment Register Records Only One of Four Marked](https://user-images.githubusercontent.com/59615855/116108300-062c1680-a671-11eb-8853-47946b098332.png)

**1626 Document**
[MD 2019 1870 Items selected to be cleared.docx](https://github.com/TheInfiniteKind/moneydance_open/files/6378296/MD.2019.1870.Items.selected.to.be.cleared.docx)

**1870 Document**
[MoneyDance_Bug_ClearingMultipleRecords.docx](https://github.com/TheInfiniteKind/moneydance_open/files/6378290/MoneyDance_Bug_ClearingMultipleRecords.docx)

**Comment by sreilly** [comment] 2021-05-11 08:20
This is 29.  duh, sorry.

**Comment by sreilly** [comment] 2021-05-18 23:42
re-closing this as it's a duplicate of #29

**Closed by sreilly** 2021-05-18 23:42 UTC
