### ISSUE TITLE
Moneybot alway throws this error: Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: ... is already set as root of another scene

### ISSUE THREAD

**Issue by yogi1967** [TheInfiniteKind/moneydance_open#21] opened 2021-04-07 15:38 UTC
Please can we eliminate this annoying console error when launching Moneybot the second time onwards..:

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: WebView@3570ae08[styleClass=root web-view]is already set as root of another scene
	at javafx.graphics/javafx.scene.Scene$8.invalidated(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.setRoot(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.<init>(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.<init>(Unknown Source)
	at com.moneydance.apps.md.view.gui.bot.RobotBrowser.addToPanel(RobotBrowser.java:289)
	at com.moneydance.apps.md.view.gui.bot.RobotBrowser.lambda$addToPanel$9(RobotBrowser.java:292)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
```

**Comment by sreilly** [comment] 2021-04-09 23:42
I believe this is a duplicate of #20

**Closed by sreilly** 2021-04-09 23:42 UTC
Labels: desktop
